version: '3.3'
services:
  alist-ex:
    image: docker.io/xhofe/alist:beta
    # If you need ffmpeg, use this image: ghcr.io/wy580477/alist-ex-container:latest-ffmpeg
    container_name: alist
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/alist:/data
      # Volume for storing data.
    environment:
      ARIA2_TOKEN: "token"
      # Aria2 RPC token, recommend strong password.
      ARIA2_TRACKER_UPDATE: "enable"
      # Auto update Aria2 tracker list on container start, set to "disable" to disable this function.
      TZ: UTC
      # Timezone

      # The following envs are list of ports listened on localhost. 
      # You don't need to change them unless you have port conflict.
      ALIST_PORT: 61600
      ARIA2_PORT: 61601
      QBT_WEBUI_PORT: 61602
